remove make system (we are not using c.) add shell

diff --git a/mosaic-kit b/mosaic-kit
--- a/mosaic-kit
+++ b/mosaic-kit
@@ -1,5 +1,22 @@
 #/bin/sh
+# Kieran Lavato, 2024
+#
+# For information regarding licensing, look at the LICENSE file provided within the repository.
+#
+# mosaic-kit is itself a package installer to create the desktop enviorment within Mosaic Linux.
+# To change the configuration, change the config.cfg file within the repository.
+# Otherwise, everything will be set to its default settings.
+#
 
+
+
+#--------------config file check-----------------------
+CONFIG_FILE="./config.cfg"
+if [ ! -f "$CONFIG_FILE" ]; then
+    echo "Configuration file '$CONFIG_FILE' not found!"
+    exit 1
+fi
+source "$CONFIG_FILE"
 #-----------------------help screen--------------------
 mosaic_help() {
 	echo "mosaic-kit alpha, version 0.0.1"
@@ -15,7 +32,7 @@ mosaic_help() {
 
 #------------------------build script------------------
 mosaic_build() {
-	echo "build"
+	ls $PREFIX
 }
 
 #-------------------------install script---------------
